### ISSUE TITLE
troubleshooting crashes?

### ISSUE THREAD

**Issue by selaromdotnet** [fvdpol/MM-ExportITunesLibraryXml#1]
Firstly thanks for posting this on git to share! I'm hoping to sync my MM playlists over to Traktor but even after using your latest script, Traktor crashes when opening the exported iTunes playlist file...

All it gives me is a binary mini-dump so I'm not sure how I can use this to troubleshoot and debug the script. How did you do this to fix problems in the past? I'd like to help if I can but so far I can't figure out what the problem is. any ideas?

**Comment by selaromdotnet** [comment]
aha! turns out I just needed to restart MM, your script worked a treat, I'm finally in sync!

many thanks again!

**Comment by fvdpol** [comment]
@selaromdotnet, I'm in progress of moving the script into a "real" MediaMonkey4 plugin; which can be installed using an .mmip extension package.  This should also remove the need to fiddle with the ini files/restart MediaMonkey.  

You can find the new package in the 'mmip-package' branch.  Package downloadable at https://github.com/fvdpol/MM-ExportITunesLibraryXml/blob/mmip-package/ExportITunesXML.MMIP
