### ISSUE TITLE
Key to Work on Serato

### ISSUE THREAD

**Issue by fernandolcardoso** [fvdpol/MM-ExportITunesLibraryXml#10]
Hello Developer, Forgive my English, I hope to contribute somehow with your project.

I ran several tests in the script and identified the problem with Serato, just enter the <key> Persistent ID </ key>

In the link below, there is a brief description of how to generate the code in this key, I tried to do but did not have time to finish due to my limited knowledge in this language.

https://stackoverflow.com/questions/13795842/linking-itunes-itc2-files-and-ituneslibrary-xml

I believe that with your knowledge, you can generate these keys and solve the problem with Serato.

hug

**Comment by fernandolcardoso** [comment]
I found a great solution for Serato DJ users.

Between lines 285 to 311, add the following line:
* addKey fout, "Persistent ID", "null", "string"

**Comment by fernandolcardoso** [comment]
Here's a new tip for those who use the Collation column in MediaMonkey, add the row below to export the column.
* addKey fout, "Grouping", Song.Grouping, "string"

**Comment by fvdpol** [comment]
thanks for your feedback Fernando. I'll check if/how adding these fields to the xml would impact compatibility with other software. Would be great if this plugin would support Serato out of the box. 

What versions of MediaMonkey/Plugin/Serato have you been using?

**Comment by fvdpol** [comment]
Hi Fernando; I updated the plugin to add the Persistent ID and Grouping; but for Persistent ID I used the MediaMonkey internal database ID to ensure it's value is unique.  

Can you please check if this change works for you? You can use latest commit from github or attached (unreleased) mmip
[ExportITunesXML.zip](https://github.com/fvdpol/MM-ExportITunesLibraryXml/files/2496674/ExportITunesXML.zip)

**Comment by fvdpol** [comment]
Quick update; I also integrated some changes to make Pioneer Recordbox accept the exported files. The handling of nested playlists may also be helpful for Serato DJ.  New build attached. Could you please let me know how/if this works?
[ExportITunesXML serato+recordbox.zip](https://github.com/fvdpol/MM-ExportITunesLibraryXml/files/2497013/ExportITunesXML.serato%2Brecordbox.zip)

**Comment by fernandolcardoso** [comment]
Frank, I exported the iTunes file and all playlists and songs were exported and uploaded properly by the Serato DJ.

![image](https://user-images.githubusercontent.com/16019127/47255601-1f253280-d44a-11e8-846b-2bb287f8b83f.png)

I think it's perfect, the only comment here is on the question of where the file should be saved by default.

**Comment by fvdpol** [comment]
Thanks for your feedback. Great to hear that the exported xml format works with Serato.

The default file location is in the same place where MediaMonkey stores the database (which is in this %appata% directory. You can change the file name and/or location in the settings dialog. I’ll add a note to the description on github to make Serato users aware on the required location.

**Comment by fvdpol** [comment]
Closing this issue; changes included in released version v1.6.3
(https://github.com/fvdpol/MM-ExportITunesLibraryXml/releases/tag/v1.6.3)
