### ISSUE TITLE
Working with DJ Software Rekordbox

### ISSUE THREAD

**Issue by tobyprin** [fvdpol/MM-ExportITunesLibraryXml#11]
Hi!
I was wondering if you have had any requests to include Pioneer's software Rekordbox within your code / testing?!

I'm using Win 10 64bit - Rekordbox 5.4.0 - and gave it a few basic attempts as I have zero programming knowledge!! MediaMonkey is 4.1.21 - and I have your export code of 1.6.2 - my iTunes version is 12.7.3

Initially Rekordbox did not see anything in the exported XML - so I opened the original iTunes XML in notepad, and compared it to the MediaMonkey exported XML. The main Header and footer were slightly different - so I copied and pasted these, and saved as a new test file.

Upon testing in Rekordbox - the XML was loaded to a degree - I was able to see the playlists created by MediaMonkey, and initially the playlists imported to MM from iTunes were displayed, but then disappeared! Sadly - not all of the tracks in the library were displayed, and none of them could be loaded!!

Anyway - perhaps getting away from iTunes and back to MM is further away than I hoped!!
Toby

**Comment by fvdpol** [comment]
Hi Toby, I did not get any request for inclusion of Pioneer's Recordbox, but am more than happy to add this feature.  

As I do not own a license of Recordbox I'll need your help in testing. Can you send me some example file that is working (from iTunes) + an example export from created by the MediaMonkey plugin for same files?

**Comment by fvdpol** [comment]
Hi Toby, I did some tests with the trial version of Recordbox, and found some issues that prevented Recordbox from reading the MM Export.  

Can you please test attached unreleased version of the addin (or build yourself from Github sources) and provide feedback?  T
Thanks, 
Frank
[ExportITunesXML serato+recordbox.zip](https://github.com/fvdpol/MM-ExportITunesLibraryXml/files/2497008/ExportITunesXML.serato%2Brecordbox.zip)

**Comment by fvdpol** [comment]
Closing this issue; changes included in released version v1.6.3
(https://github.com/fvdpol/MM-ExportITunesLibraryXml/releases/tag/v1.6.3)
