### ISSUE TITLE
Feature request: ability to NOT export the playlists

### ISSUE THREAD

**Issue by fvdpol** [fvdpol/MM-ExportITunesLibraryXml#12]
Feature request by MediaMonkey forum member "Biggus_Dickus"
http://www.mediamonkey.com/forum/memberlist.php?mode=viewprofile&u=96106:

is there a way to let script export songs only (without playlist export)?

The reason is, I use a combination of Mediamonkey and Musicbee. Mediamonkey Gold for syncing my Android and MediaMonkey-Android-Pro for playback from my phone. But I prefer Musicbee for tagging and when I playback from my laptop, cause in my opinion, it has a better audio engine and is more configurable. MediaMonkey is great, while syncing back ratings and playcount/playdate. And MMA is great too, supporting multiple artists, genres. Musicbee isn't supported by android players. But Musicbee easily imports ratings made in Monkey, but not playcount/playdate. With importing iTunes.xml I can import playcount/playdate. But it imports playlist too, which already exists in Musicbee and are organized in folders. So I've everytime to delete the imported. It wouldn't be difficult, having only a few, but I've nearly 60 or so.

(ref: http://www.mediamonkey.com/forum/viewtopic.php?p=450860#p450860)

**Comment by fvdpol** [comment]
Create development branch for this feature: https://github.com/fvdpol/MM-ExportITunesLibraryXml/tree/exclude-playlists-in-export

unreleased development build which includes the new functionality attached:
[ExportITunesXML.zip](https://github.com/fvdpol/MM-ExportITunesLibraryXml/files/2590113/ExportITunesXML.zip)

New option can be configured in the configuration dialog; if the 'Exclude export of Playlists' is checked the playlists will not be exported.
![image](https://user-images.githubusercontent.com/1499454/48634740-9bb61d00-e9c6-11e8-9ac8-a25e5dc4b4cf.png)

**Comment by SchwanzusLongus** [comment]
Works great! Helps me a lot. Better than manually erase playlist area. Thx!!!!

**Comment by fvdpol** [comment]
@SchwanzusLongus, the change has been merged in the main development branch, and will be included in next release v1.6.4. 

Can you please let me know which version(s)/platform/etc. you used for Musicbee so I can update this in the documentation (readme.md)

**Comment by SchwanzusLongus** [comment]
I use Musicbee Version 3.2.6827 for Windows.
XML Output works fine. Play/Skipcount and last played date were also imported correctly.

**Comment by fvdpol** [comment]
Thanks. Updated in the readme.md.  Closing this issue
